In [13]:
import pandas as pd
import numpy as np

In [45]:
df = pd.read_csv("./data/total_df.csv")

In [46]:
df.head()

zip_code  Yearly_Avg_Zip  FL_Unemployment  year  total_pop  households  \
0     33160     1988.000000            5.525  2015      39235       19187   
1     33025     1433.250000            5.525  2015      60994       21770   
2     33139     2046.250000            5.525  2015      38035       20149   
3     33024     1356.083333            5.525  2015      71860       22838   
4     32256     1074.833333            5.525  2015      41609       18606   

   male_pop  female_pop  median_age  male_under_5  ...  \
0     19087       20148        48.8           772  ...   
1     28737       32257        33.4          2338  ...   
2     20756       17279        38.8           938  ...   
3     35172       36688        37.6          2379  ...   
4     19462       22147        33.7          1009  ...   

   occupation_sales_office  occupation_services  \
0                   5554.0               2793.0   
1                   9833.0               5714.0   
2                   5834.0               6648.0   
3                  11047.0               7175.0   
4                   6483.0               3406.0   

   management_business_sci_arts_employed  sales_office_employed  \
0                                 8276.0                 5554.0   
1                                11785.0                 9833.0   
2                                 9524.0                 5834.0   
3                                10101.0                11047.0   
4                                10984.0                 6483.0   

   in_grades_1_to_4  in_grades_5_to_8  in_grades_9_to_12  in_school  \
0              1312               994               1283       6732   
1              3150              3155               3604      18386   
2               922               690                491       5580   
3              3785              3863               3637      19756   
4              1854              1751               1887      10474   

   in_undergrad_college  FLSTHPI_Yearly_Avg  
0                  1737            348.4425  
1                  5038            348.4425  
2                  1745            348.4425  
3                  5345            348.4425  
4                  2926            348.4425  

[5 rows x 218 columns]

In [47]:
df.year.unique()

array([2015, 2016, 2017, 2018])

In [48]:
df.shape

(480, 218)

In [49]:
df.columns.tolist()

['zip_code',
 'Yearly_Avg_Zip',
 'FL_Unemployment',
 'year',
 'total_pop',
 'households',
 'male_pop',
 'female_pop',
 'median_age',
 'male_under_5',
 'male_5_to_9',
 'male_10_to_14',
 'male_15_to_17',
 'male_18_to_19',
 'male_20',
 'male_21',
 'male_22_to_24',
 'male_25_to_29',
 'male_30_to_34',
 'male_35_to_39',
 'male_40_to_44',
 'male_45_to_49',
 'male_50_to_54',
 'male_55_to_59',
 'male_65_to_66',
 'male_67_to_69',
 'male_70_to_74',
 'male_75_to_79',
 'male_80_to_84',
 'male_85_and_over',
 'female_under_5',
 'female_5_to_9',
 'female_10_to_14',
 'female_15_to_17',
 'female_18_to_19',
 'female_20',
 'female_21',
 'female_22_to_24',
 'female_25_to_29',
 'female_30_to_34',
 'female_35_to_39',
 'female_40_to_44',
 'female_45_to_49',
 'female_50_to_54',
 'female_55_to_59',
 'female_60_to_61',
 'female_62_to_64',
 'female_65_to_66',
 'female_67_to_69',
 'female_70_to_74',
 'female_75_to_79',
 'female_80_to_84',
 'female_85_and_over',
 'population_1_year_and_over',
 'population_3_years_o

In [10]:
for col in df_2015.columns: print(col)

zip_code
Yearly_Avg_Zip
FL_Unemployment
year
Encoded_Zip
total_pop
households
male_pop
female_pop
median_age
male_under_5
male_5_to_9
male_10_to_14
male_15_to_17
male_18_to_19
male_20
male_21
male_22_to_24
male_25_to_29
male_30_to_34
male_35_to_39
male_40_to_44
male_45_to_49
male_50_to_54
male_55_to_59
male_65_to_66
male_67_to_69
male_70_to_74
male_75_to_79
male_80_to_84
male_85_and_over
female_under_5
female_5_to_9
female_10_to_14
female_15_to_17
female_18_to_19
female_20
female_21
female_22_to_24
female_25_to_29
female_30_to_34
female_35_to_39
female_40_to_44
female_45_to_49
female_50_to_54
female_55_to_59
female_60_to_61
female_62_to_64
female_65_to_66
female_67_to_69
female_70_to_74
female_75_to_79
female_80_to_84
female_85_and_over
population_1_year_and_over
population_3_years_over
pop_5_years_over
pop_16_over
pop_25_years_over
pop_25_64
not_us_citizen_pop
median_income
income_per_capita
income_less_10000
income_10000_14999
income_15000_19999
income_20000_24999
income_25000_29999


In [11]:
no_race.year.unique()

array([2015, 2016, 2017, 2018])

In [13]:
df_2016.year.unique()

array([2016])

In [16]:
df_2017.year.unique()

array([2017])

In [17]:
df_2018.year.unique()

array([2018])

In [25]:
df_lst = [df_2015, df_2016, df_2017, df_2018]

In [12]:
no_race.shape

(480, 218)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV, GridSearchCV

sns.set_palette('colorblind')

In [ ]:
x_train, x_test, y_train, y_test = x_train, x_test, y_train, y_test = train_test_split(df.drop(columns = 'Yearly_Avg_Zip'), df.Yearly_Avg_Zip)

In [37]:
rf = RandomForestRegressor()
rf.fit(x_train, y_train)

RandomForestRegressor()

In [38]:
rf.score(x_test, y_test)

0.6640436384312323

In [39]:
df_2015.shape

(112, 218)

In [40]:
df.head()

zip_code  Yearly_Avg_Zip  FL_Unemployment  year  Encoded_Zip  total_pop  \
0     33160     1988.000000            5.525  2015           73      39235   
1     33025     1433.250000            5.525  2015           41      60994   
2     33139     2046.250000            5.525  2015           61      38035   
3     33024     1356.083333            5.525  2015           40      71860   
4     32256     1074.833333            5.525  2015           10      41609   

   households  male_pop  female_pop  median_age  ...  occupation_sales_office  \
0       19187     19087       20148        48.8  ...                   5554.0   
1       21770     28737       32257        33.4  ...                   9833.0   
2       20149     20756       17279        38.8  ...                   5834.0   
3       22838     35172       36688        37.6  ...                  11047.0   
4       18606     19462       22147        33.7  ...                   6483.0   

   occupation_services  management_business_sci_arts_employed  \
0               2793.0                                 8276.0   
1               5714.0                                11785.0   
2               6648.0                                 9524.0   
3               7175.0                                10101.0   
4               3406.0                                10984.0   

   sales_office_employed  in_grades_1_to_4  in_grades_5_to_8  \
0                 5554.0              1312               994   
1                 9833.0              3150              3155   
2                 5834.0               922               690   
3                11047.0              3785              3863   
4                 6483.0              1854              1751   

   in_grades_9_to_12  in_school  in_undergrad_college  FLSTHPI_Yearly_Avg  
0               1283       6732                  1737            348.4425  
1               3604      18386                  5038            348.4425  
2                491       5580                  1745            348.4425  
3               3637      19756                  5345            348.4425  
4               1887      10474                  2926            348.4425  

[5 rows x 218 columns]

In [41]:
df.year.unique()

array([2015])

In [ ]:
forest_2015['test_score']